# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Simulate an MCMC-based model for visuomotor rotation.
#' 
#' @param optimal A numeric vector containing the optimal reach direction.
#' @param cost_width Width of the cost function.
#' @param forget_rate Forgetting rate.
#' @param proposal_variance Width of the proposal distribution.
#' 
#' @examples
#' optimal <- c(rep(0, 8), rep(30, 80))
#' sims <- simulate_mcmc(optimal = optimal, 
#'                       cost_width = 5,
#'                       forget_rate = 0.9,
#'                       proposal_variance = 4.5)
#' plot(optimal, type = 'l')
#' lines(sims, col = 'red')
#' @export
simulate_mcmc <- function(optimal, cost_width, forget_rate, proposal_variance) {
    .Call('ssmcmc_simulate_mcmc', PACKAGE = 'ssmcmc', optimal, cost_width, forget_rate, proposal_variance)
}

#' Simulate a state space model for visuomotor rotation.
#' 
#' @param optimal A numeric vector containing the optimal reach direction.
#' @param learn_rate Learning rate.
#' @param forget_rate Forgetting rate.
#' @param process_variance State noise.
#' @param execution_variance Execution noise.
#' 
#' @examples
#' optimal <- c(rep(0, 8), rep(30, 80))
#' sims <- simulate_ssm(optimal = optimal, 
#'                      learn_rate = 0.15,
#'                      forget_rate = 0.94,
#'                      process_variance = 1,
#'                      execution_variance = 5)
#' plot(optimal, type = 'l')
#' lines(sims, col = 'red')
#' @export
simulate_ssm <- function(optimal, learn_rate, forget_rate, process_variance, execution_variance) {
    .Call('ssmcmc_simulate_ssm', PACKAGE = 'ssmcmc', optimal, learn_rate, forget_rate, process_variance, execution_variance)
}

